#!/bin/bash

function get_errors {

	local log_file_path=$1
	local dir=$2
	local name=${log_file_path: 6:-4}
	local name+=".log"
	awk -F ' ' '/ 400 / || / 401 / || / 403 / || / 404 / || / 500 / || / 501 / || / 502 / || / 503 / { print $0 }' $log_file_path >> $dir/"$name"

}
