#!/bin/bash

function sort_by_response_code {
	
	local log_file_path=$1
	local dir=$2
	local name=${log_file_path: 6:-4}
	local name+=".log"
	awk -F ' ' '{ print $10, $0 }' $log_file_path | sort >> $dir/"$name"
}
