#!/bin/bash

function generate_response_code {

	local response_code=""
	local response_code_num=$(( $RANDOM % 10 + 1 ))
	
	case $response_code_num in
		1)
		# OK response code - the request has succeeded
			response_code="200"
			;;
		2)
		# The request has been fulfiled and resulted in a new resource being created
			response_code="201"
			;;
		3)
		# Bad request - the request cannot be fulfilled due to bad syntax
			response_code="400"
			;;
		4)
		# Unauthorized - when authentication is possible but has failed
			response_code="401"
			;;
		5)
		# Forbidden - error code for user not authorized to perform the operation or the resource is unavailable for some reason
			response_code="403"
			;;
		6)
		# Not found - the requested resource could not be found but may be available again in the future
			response_code="404"
			;;
		7)
		# Internal server error - a generic error message, given when no more specific message is suitable
			response_code="500"
			;;
		8)
		# Not implemented - the server either does not recognize the request method or it lacks the ability to fulfill the request
			response_code="501"
			;;
		9)
		# Bad gateway - the server was acting as a gateway or proxy and received an invalid response from the upstream server
			response_code="502"
			;;
		10)
		# Service inavailable - the server is currently unavailable
			response_code="503"
			;;
	esac

	echo $response_code

}
