#!/bin/bash

function generate_method {
	
	local method=""
	local method_num=$(( $RANDOM % 5 + 1 ))

	case $method_num in
		1)
			method="GET"
			;;
		2)
			method="POST"
			;;
		3)
			method="PUT"
			;;
		4)
			method="PATCH"
			;;
		5)
			method="DELETE"
			;;
	esac

	local target=""
	local target_num=$(( $RANDOM % 14 + 1))
	
	case $target_num in
		1)
			target="/status"
			;;
		2)
			target="/id"
			;;
		3)
			target="/profile"
			;;
		4)
			target="/deal_in"
			;;
		5)
			target="/deal_out"
			;;
		6)
			target="/position"
			;;
		7)
			target="/buying_price"
			;;
		8)
			target="/selling_price"
			;;
		9)
			target="/open_time"
			;;
		10)
			target="/close_time"
			;;
		11)
			target="/volume"
			;;
		12)
			target="/profit"
			;;
		13)
			target="/balance"
			;;
		14)
			target="/server_id"
			;;
esac

link=""
link_num=$(( $RANDOM % 3 + 1 ))

case $link_num in
	1)
		link="HTTP/1.0"
		;;
	2)
		link="HTTP/1.1"
		;;
	3)
		link="HTTP/2"
		;;
esac

	echo "$method $target $link"

}
