#!/bin/bash

function generate_username {

	local username=""
	local username_num=$(( $RANDOM % 6 + 1 ))
	
	case $username_num in
		1)
			username="user0a"
			;;
		2)
			username="user1b"
			;;
		3)
			username="user2c"
			;;
		4)
			username="user3d"
			;;
		5)
			username="user4e"
			;;
		6)
			username="user5f"
			;;
		7)
			username="user6g"
			;;
	esac

	echo $username

}
